### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by dschmide** [dschmide/Waldmeister-Outdoors#12]

**Comment by sfkeller** [comment]
Pls. reopen this issue (and don't close issues which are "Ready to review" in general).

Bitte folgendes refaktorsieren (wie in Mails und mündlich angesprochen): 

1. Ganzes Repo umbenennen von Waldmeister => Waldmeister-Outdoors. 
2. Sub-Directory in https://github.com/dschmide/Waldmeister/tree/master/backend : /waldmeister_map/ => /restful_api/, 
3. sowie /waldmeister_outdoors/ => /config/
